export const GET_CUSTOMERS = 'GET_CUSTOMERS';
export const SET_USERS_STATUS = 'SET_USERS_STATUS';
export const SET_USERS_PAGE = 'SET_USERS_PAGE';
export const SET_USERS_LIMIT = 'SET_USERS_LIMIT';
export const SET_USERS_SEARCH = 'SET_USERS_SEARCH';
