export const SET_EVENTS_STATUS = 'SET_EVENTS_STATUS';
export const GET_EVENTS = 'GET_EVENTS';
export const GET_EVENT = 'GET_EVENT';
export const CHANGE_EVENTS_SEARCH_PARAMS = 'CHANGE_EVENTS_SEARCH_PARAMS';
