export const SET_SERVICES_STATUS = 'SET_SERVICES_STATUS';
export const GET_SERVICES = 'GET_SERVICES';
export const GET_SERVICE = 'GET_SERVICE';
export const CHANGE_SERVICES_SEARCH_PARAMS = 'CHANGE_SERVICES_SEARCH_PARAMS';
export const DELETE_SERVICE = 'DELETE_SERVICE';
